# load libraries needed for GLAHD analysis)
suppressMessages(require(HIEv))
suppressMessages(require(plotrix))
suppressMessages(require(magicaxis))
suppressMessages(require(doBy))
suppressMessages(require(minpack.lm))
suppressMessages(require(hydromad))
suppressMessages(require(data.table))
suppressMessages(require(MASS))
suppressMessages(require(plotBy))
suppressMessages(require(lubridate))
suppressMessages(require(plantecophys))
suppressMessages(require(dplyr))
suppressMessages(require(car))


source(file="C:/Repos/GLAHD/R/generic_functions.R")
source(file="C:/Repos/GLAHD/R/adderrorbars.R")
source(file="C:/Repos/GLAHD/R/GLAHD_analysis_functions.R")
